site_name: AlgoFlow Documentation
site_url: https://algoflow-quant.github.io/algoflow
repo_url: https://github.com/algoflow-quant/algoflow

theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      toggle:
        icon: material/brightness-7
        name: Dark mode
    - scheme: slate
      primary: indigo
      toggle:
        icon: material/brightness-4
        name: Light mode
  features:
    - navigation.sections
    - navigation.top
    - search.suggest

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [data_pipeline]
          options:
            docstring_style: google
            show_source: true

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - tables
  - attr_list
  - md_in_html

nav:
  - Home: index.md
  - Data Pipeline:
      - Overview: data_pipeline/overview.md
      - DAGs:
          - Historical: data_pipeline/dags/historical.md
          - Daily: data_pipeline/dags/daily.md
      - Components:
          - Tickers: data_pipeline/components/tickers.md
          - Validation: data_pipeline/components/validation.md
          - YfinancePipeline: data_pipeline/components/yfinance_pipeline.md
          - YfinanceClient: data_pipeline/components/yfinance_client.md
