version: '3.8'

services:
  # PostgreSQL with TimescaleDB for time-series data
  postgres:
    image: timescale/timescaledb:latest-pg15
    container_name: algoflow_sec_master_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sec_master_dev
    ports:
      - "5432:5432"
    volumes:
      # Auto-run SQL scripts from init folder
      - ./sec_master_db/init:/docker-entrypoint-initdb.d
      # Persist data between container restarts
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - algoflow_network

  # Adminer - Database management UI
  adminer:
    image: adminer
    container_name: algoflow_adminer
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: postgres
    depends_on:
      - postgres
    networks:
      - algoflow_network

  # Dozzle - Real-time Docker log viewer
  dozzle:
    image: amir20/dozzle:latest
    container_name: algoflow_dozzle
    ports:
      - "9999:8080"
    environment:
      DOZZLE_LEVEL: info
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - algoflow_network

  # Future services can be added here:
  # api:
  #   build: ./api
  #   depends_on:
  #     - postgres
  #   networks:
  #     - algoflow_network

volumes:
  postgres_data:
    driver: local

networks:
  algoflow_network:
    driver: bridge