name: Auto Version Bump

# Trigger when PR from dev to main is merged
on:
  pull_request:
    types: [closed]
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  bump-version:
    # Only run if PR was merged (not just closed) and source branch was dev
    if: github.event.pull_request.merged == true && github.event.pull_request.head.ref == 'dev'
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout main branch with full history (admin PAT bypasses protection)
      - name: Checkout main
        uses: actions/checkout@v3
        with:
          ref: main
          fetch-depth: 0
          token: ${{ secrets.VERSION_BUMP_TOKEN }}

      # Step 3: Configure git
      - name: Configure Git
        run: |
          git config --global user.name "algoflow-bot[bot]"
          git config --global user.email "algoflow-bot[bot]@users.noreply.github.com"

      # Step 4: Install Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Step 5: Install commitizen
      - name: Install commitizen
        run: pip install commitizen

      # Step 6: Run cz bump (auto-detects version from commits)
      - name: Bump version with commitizen
        run: |
          cz bump --yes --changelog
        env:
          SKIP_PRE_COMMIT: 1

      # Step 7: Push changes to main
      - name: Push changes to main
        run: |
          git push origin main
          git push origin --tags

      # Step 8: Merge main back to dev to sync version
      - name: Sync version back to dev
        run: |
          git fetch origin dev:dev
          git checkout dev
          git merge main --no-ff -m "chore: sync version bump from main [skip ci]"
          git push origin dev
