name: Lint Commits
on: [pull_request]

# Permission so that github action can checkout
permissions:
    contents: read
    pull-requests: read

jobs:
    commitlint:
        runs-on: ubuntu-latest
        steps:
            # Step 1: "Check-out" the code
            - uses: actions/checkout@v3
              with:
                fetch-depth: 0 # 0 gets all commits in a pr

            # Step 2: Check commits and enforce rules
            - uses: wagoid/commitlint-github-action@v5
              with:
                configFile: .commitlintrc.json
